service: ca-housing-price-prediction

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-2
  apiGateway: { shouldStartNameWithService: true }

package:
  #  include:
  #    - include-me.py
  #    - include-me-dir/**
  exclude:
    - node_modules/**
    - .vscode/**
    - __pycache__/**
    - .ipynb_checkpoints/**
    - (*).ipynb

functions:
  predict-price:
    handler: handler.predict
    memorySize: 512
    timeout: 30
    package: {} # This fixes TypeError: Cannot read property 'artifact' of undefined when deplying a single function to Lambda
    events:
      - http:
          path: get-price
          method: get
          request:
            parameters:
              querystrings:
                medInc: true
                houseAge: true
                aveRooms: true
                aveBedrms: true
                population: true
                aveOccup: true
                latitude: true
                longitude: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    strip: false
