service: spacy-nlp-api

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-2
  apiGateway: { shouldStartNameWithService: true }

package:
#  include:
#    - include-me.py
#    - include-me-dir/**
  exclude:
    - node_modules/**
    - .vscode/**
    - __pycache__/**
    - .ipynb_checkpoints/**
    - (*).ipynb

functions:
  recognize-named-entities:
    handler: handler.handle_request
    memorySize: 1536
    timeout: 30
    package: {} # This fixes TypeError: Cannot read property 'artifact' of undefined when deplying a single function to Lambda
    events:
      - http:
          path: ner
          method: post

custom:
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
    zip: true
    strip: false
    noDeploy: []
    useDownloadCache: true
    useStaticCache: true

plugins:
  - serverless-python-requirements
